// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANXnDwzq4z6tt7iV75CQgp8eg7w2l_2g0',
    appId: '1:608957088693:web:52e5b07f47426535f80ffc',
    messagingSenderId: '608957088693',
    projectId: 'root-flutter',
    authDomain: 'root-flutter.firebaseapp.com',
    storageBucket: 'root-flutter.appspot.com',
    measurementId: 'G-Z64785LJB2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSRPI0Xu8Y82d1eKL8GGQXpaxUvlroDSI',
    appId: '1:608957088693:android:2f43285732d357f5f80ffc',
    messagingSenderId: '608957088693',
    projectId: 'root-flutter',
    storageBucket: 'root-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzrQzXHxSkpM7jpKNLvtlRZ3LhGWoBNg8',
    appId: '1:608957088693:ios:d1c473b937147048f80ffc',
    messagingSenderId: '608957088693',
    projectId: 'root-flutter',
    storageBucket: 'root-flutter.appspot.com',
    iosBundleId: 'vn.root.app.dev',
  );
}
